In [1]:
import pandas as pd
import numpy as np
import string

# a) EngAlph Series with alphabets
EngAlph = pd.Series(list(string.ascii_lowercase))
print("a) EngAlph:\n", EngAlph)


a) EngAlph:
 0     a
1     b
2     c
3     d
4     e
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object


In [2]:
Vowels = pd.Series([0, 0, 0, 0, 0], index=['a', 'e', 'i', 'o', 'u'])
print("\nb) Vowels:\n", Vowels)
print("Is Vowels empty?:", Vowels.empty)


b) Vowels:
 a    0
e    0
i    0
o    0
u    0
dtype: int64
Is Vowels empty?: False


In [3]:
friends_dict = {'Alice': 101, 'Bob': 102, 'Charlie': 103, 'David': 104, 'Eva': 105}
Friends = pd.Series(friends_dict)
print("\nc) Friends:\n", Friends)



c) Friends:
 Alice      101
Bob        102
Charlie    103
David      104
Eva        105
dtype: int64


In [4]:
MTseries = pd.Series(dtype='float64')
print("\nd) MTseries:\n", MTseries)
print("Is MTseries empty?:", MTseries.empty)



d) MTseries:
 Series([], dtype: float64)
Is MTseries empty?: True


In [5]:
# e) MonthDays from numpy array
days_array = np.array([31,28,31,30,31,30,31,31,30,31,30,31])
MonthDays = pd.Series(days_array, index=range(1, 13))
print("\ne) MonthDays:\n", MonthDays)


e) MonthDays:
 1     31
2     28
3     31
4     30
5     31
6     30
7     31
8     31
9     30
10    31
11    30
12    31
dtype: int64


In [6]:
Vowels[:] = 10
print("a) Vowels:\n", Vowels)


a) Vowels:
 a    10
e    10
i    10
o    10
u    10
dtype: int64


In [7]:
Vowels = Vowels / 2
print("\nb) Vowels after division:\n", Vowels)



b) Vowels after division:
 a    5.0
e    5.0
i    5.0
o    5.0
u    5.0
dtype: float64


In [8]:

# c) Create Vowels1 series
Vowels1 = pd.Series([2, 5, 6, 3, 8], index=['a', 'e', 'i', 'o', 'u'])
print("\nc) Vowels1:\n", Vowels1)



c) Vowels1:
 a    2
e    5
i    6
o    3
u    8
dtype: int64


In [9]:
# d) Add Vowels and Vowels1
Vowels3 = Vowels + Vowels1
print("\nd) Vowels3 (Sum):\n", Vowels3)



d) Vowels3 (Sum):
 a     7.0
e    10.0
i    11.0
o     8.0
u    13.0
dtype: float64


In [10]:
# e) Subtract, Multiply, Divide
print("\ne) Subtract:\n", Vowels1 - Vowels)
print("Multiply:\n", Vowels1 * Vowels)
print("Divide:\n", Vowels1 / Vowels)


e) Subtract:
 a   -3.0
e    0.0
i    1.0
o   -2.0
u    3.0
dtype: float64
Multiply:
 a    10.0
e    25.0
i    30.0
o    15.0
u    40.0
dtype: float64
Divide:
 a    0.4
e    1.0
i    1.2
o    0.6
u    1.6
dtype: float64


In [11]:
# f) Rename index of Vowels1
Vowels1.index = ['A', 'E', 'I', 'O', 'U']
print("\nf) Renamed Vowels1:\n", Vowels1)



f) Renamed Vowels1:
 A    2
E    5
I    6
O    3
U    8
dtype: int64


In [12]:
# a) Find dimensions, size, and values
print("a) Properties:")
print("EngAlph - Dim:", EngAlph.ndim, ", Size:", EngAlph.size, ", Values:", EngAlph.values)
print("Vowels - Dim:", Vowels.ndim, ", Size:", Vowels.size, ", Values:", Vowels.values)
print("Friends - Dim:", Friends.ndim, ", Size:", Friends.size, ", Values:", Friends.values)
print("MTseries - Dim:", MTseries.ndim, ", Size:", MTseries.size, ", Values:", MTseries.values)
print("MonthDays - Dim:", MonthDays.ndim, ", Size:", MonthDays.size, ", Values:", MonthDays.values)


a) Properties:
EngAlph - Dim: 1 , Size: 26 , Values: ['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l' 'm' 'n' 'o' 'p' 'q' 'r'
 's' 't' 'u' 'v' 'w' 'x' 'y' 'z']
Vowels - Dim: 1 , Size: 5 , Values: [5. 5. 5. 5. 5.]
Friends - Dim: 1 , Size: 5 , Values: [101 102 103 104 105]
MTseries - Dim: 1 , Size: 0 , Values: []
MonthDays - Dim: 1 , Size: 12 , Values: [31 28 31 30 31 30 31 31 30 31 30 31]


In [13]:
# b) Rename MTseries
SeriesEmpty = MTseries.rename("SeriesEmpty")
print("\nb) Renamed MTseries as SeriesEmpty:\n", SeriesEmpty)




b) Renamed MTseries as SeriesEmpty:
 Series([], Name: SeriesEmpty, dtype: float64)


In [14]:
# c) Rename index
MonthDays.index.name = 'monthno'
Friends.index.name = 'Fname'
print("\nc) Named MonthDays index as 'monthno':\n", MonthDays)
print("Named Friends index as 'Fname':\n", Friends)


c) Named MonthDays index as 'monthno':
 monthno
1     31
2     28
3     31
4     30
5     31
6     30
7     31
8     31
9     30
10    31
11    30
12    31
dtype: int64
Named Friends index as 'Fname':
 Fname
Alice      101
Bob        102
Charlie    103
David      104
Eva        105
dtype: int64


In [15]:
import pandas as pd
import numpy as np
import string

# a) EngAlph: 26 English letters
EngAlph = pd.Series(list(string.ascii_lowercase))
print("a) EngAlph:\n", EngAlph)

a) EngAlph:
 0     a
1     b
2     c
3     d
4     e
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object


In [16]:
# b) Vowels
Vowels = pd.Series([0, 0, 0, 0, 0], index=['a', 'e', 'i', 'o', 'u'])
print("\nb) Vowels:\n", Vowels)
print("Is Vowels empty? ", Vowels.empty)



b) Vowels:
 a    0
e    0
i    0
o    0
u    0
dtype: int64
Is Vowels empty?  False


In [17]:
# c) Friends from dictionary
friends_dict = {'Alice': 101, 'Bob': 102, 'Charlie': 103, 'David': 104, 'Eva': 105}
Friends = pd.Series(friends_dict)
print("\nc) Friends:\n", Friends)



c) Friends:
 Alice      101
Bob        102
Charlie    103
David      104
Eva        105
dtype: int64


In [18]:
# d) MTseries: Empty Series
MTseries = pd.Series(dtype='float64')
print("\nd) MTseries:\n", MTseries)
print("Is MTseries empty? ", MTseries.empty)


d) MTseries:
 Series([], dtype: float64)
Is MTseries empty?  True


In [19]:
# e) MonthDays
days_array = np.array([31,28,31,30,31,30,31,31,30,31,30,31])
MonthDays = pd.Series(days_array, index=range(1,13))
print("\ne) MonthDays:\n", MonthDays)



e) MonthDays:
 1     31
2     28
3     31
4     30
5     31
6     30
7     31
8     31
9     30
10    31
11    30
12    31
dtype: int64


In [20]:
Vowels[:] = 10
print("\na) Vowels set to 10:\n", Vowels)



a) Vowels set to 10:
 a    10
e    10
i    10
o    10
u    10
dtype: int64


In [21]:
# b) Divide all by 2
Vowels = Vowels / 2
print("\nb) Vowels divided by 2:\n", Vowels)



b) Vowels divided by 2:
 a    5.0
e    5.0
i    5.0
o    5.0
u    5.0
dtype: float64


In [22]:
# c) Vowels1
Vowels1 = pd.Series([2, 5, 6, 3, 8], index=['a', 'e', 'i', 'o', 'u'])
print("\nc) Vowels1:\n", Vowels1)



c) Vowels1:
 a    2
e    5
i    6
o    3
u    8
dtype: int64


In [23]:
# d) Add Vowels + Vowels1
Vowels3 = Vowels + Vowels1
print("\nd) Vowels3 (Vowels + Vowels1):\n", Vowels3)



d) Vowels3 (Vowels + Vowels1):
 a     7.0
e    10.0
i    11.0
o     8.0
u    13.0
dtype: float64


In [24]:
# e) Subtract, Multiply, Divide
print("\ne) Vowels1 - Vowels:\n", Vowels1 - Vowels)
print("   Vowels1 * Vowels:\n", Vowels1 * Vowels)
print("   Vowels1 / Vowels:\n", Vowels1 / Vowels)


e) Vowels1 - Vowels:
 a   -3.0
e    0.0
i    1.0
o   -2.0
u    3.0
dtype: float64
   Vowels1 * Vowels:
 a    10.0
e    25.0
i    30.0
o    15.0
u    40.0
dtype: float64
   Vowels1 / Vowels:
 a    0.4
e    1.0
i    1.2
o    0.6
u    1.6
dtype: float64


In [25]:
# f) Rename labels of Vowels1
Vowels1.index = ['A', 'E', 'I', 'O', 'U']
print("\nf) Vowels1 with new labels:\n", Vowels1)



f) Vowels1 with new labels:
 A    2
E    5
I    6
O    3
U    8
dtype: int64


In [26]:
print("a) Properties:")
print("EngAlph - Dim:", EngAlph.ndim, ", Size:", EngAlph.size, ", Values:", EngAlph.values)
print("Vowels - Dim:", Vowels.ndim, ", Size:", Vowels.size, ", Values:", Vowels.values)
print("Friends - Dim:", Friends.ndim, ", Size:", Friends.size, ", Values:", Friends.values)
print("MTseries - Dim:", MTseries.ndim, ", Size:", MTseries.size, ", Values:", MTseries.values)
print("MonthDays - Dim:", MonthDays.ndim, ", Size:", MonthDays.size, ", Values:", MonthDays.values)


a) Properties:
EngAlph - Dim: 1 , Size: 26 , Values: ['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l' 'm' 'n' 'o' 'p' 'q' 'r'
 's' 't' 'u' 'v' 'w' 'x' 'y' 'z']
Vowels - Dim: 1 , Size: 5 , Values: [5. 5. 5. 5. 5.]
Friends - Dim: 1 , Size: 5 , Values: [101 102 103 104 105]
MTseries - Dim: 1 , Size: 0 , Values: []
MonthDays - Dim: 1 , Size: 12 , Values: [31 28 31 30 31 30 31 31 30 31 30 31]


In [27]:
# b) Rename MTseries to SeriesEmpty
SeriesEmpty = MTseries.rename("SeriesEmpty")
print("\nb) Renamed MTseries:\n", SeriesEmpty)


b) Renamed MTseries:
 Series([], Name: SeriesEmpty, dtype: float64)


In [28]:
# c) Index names
MonthDays.index.name = 'monthno'
Friends.index.name = 'Fname'
print("\nc) MonthDays with index name:\n", MonthDays)
print("Friends with index name:\n", Friends)


c) MonthDays with index name:
 monthno
1     31
2     28
3     31
4     30
5     31
6     30
7     31
8     31
9     30
10    31
11    30
12    31
dtype: int64
Friends with index name:
 Fname
Alice      101
Bob        102
Charlie    103
David      104
Eva        105
dtype: int64


In [29]:
print("d) 3rd and 2nd value from Friends:\n", Friends.iloc[[2, 1]])

d) 3rd and 2nd value from Friends:
 Fname
Charlie    103
Bob        102
dtype: int64


In [30]:
print("e) Alphabets from 'e' to 'p':\n", EngAlph[4:16])

e) Alphabets from 'e' to 'p':
 4     e
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
dtype: object


In [31]:
print("f) First 10 values:\n", EngAlph.head(10))


f) First 10 values:
 0    a
1    b
2    c
3    d
4    e
5    f
6    g
7    h
8    i
9    j
dtype: object


In [32]:
print("g) Last 10 values:\n", EngAlph.tail(10))


g) Last 10 values:
 16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object


In [33]:
print("h) MTseries:\n", MTseries)


h) MTseries:
 Series([], dtype: float64)


In [34]:
print("8a) Months 3 to 7:\n", MonthDays.loc[3:7])


8a) Months 3 to 7:
 monthno
3    31
4    30
5    31
6    30
7    31
dtype: int64


In [35]:
print("8b) MonthDays in reverse:\n", MonthDays[::-1])


8b) MonthDays in reverse:
 monthno
12    31
11    30
10    31
9     30
8     31
7     31
6     30
5     31
4     30
3     31
2     28
1     31
dtype: int64


In [36]:
import pandas as pd

data = {
    '2014': [100.5, 150.8, 200.9, 30000, 40000],
    '2015': [12000, 18000, 22000, 30000, 45000],
    '2016': [20000, 50000, 70000, 100000, 125000],
    '2017': [50000, 60000, 70000, 80000, 90000]
}

index_labels = ['Madhu', 'Kusum', 'Kinshuk', 'Ankit', 'Shruti']

Sales = pd.DataFrame(data, index=index_labels)
print("Sales DataFrame:\n", Sales)


Sales DataFrame:
             2014   2015    2016   2017
Madhu      100.5  12000   20000  50000
Kusum      150.8  18000   50000  60000
Kinshuk    200.9  22000   70000  70000
Ankit    30000.0  30000  100000  80000
Shruti   40000.0  45000  125000  90000


In [37]:
print("10a) Row labels:\n", Sales.index)


10a) Row labels:
 Index(['Madhu', 'Kusum', 'Kinshuk', 'Ankit', 'Shruti'], dtype='object')


In [38]:
print("10b) Column labels:\n", Sales.columns)


10b) Column labels:
 Index(['2014', '2015', '2016', '2017'], dtype='object')


In [39]:
print("10c) Data types:\n", Sales.dtypes)


10c) Data types:
 2014    float64
2015      int64
2016      int64
2017      int64
dtype: object


In [40]:
print("10c) Data types:\n", Sales.dtypes)


10c) Data types:
 2014    float64
2015      int64
2016      int64
2017      int64
dtype: object


In [41]:
print("10d) Dimensions:", Sales.ndim)
print("Shape:", Sales.shape)
print("Size:", Sales.size)
print("Values:\n", Sales.values)


10d) Dimensions: 2
Shape: (5, 4)
Size: 20
Values:
 [[1.005e+02 1.200e+04 2.000e+04 5.000e+04]
 [1.508e+02 1.800e+04 5.000e+04 6.000e+04]
 [2.009e+02 2.200e+04 7.000e+04 7.000e+04]
 [3.000e+04 3.000e+04 1.000e+05 8.000e+04]
 [4.000e+04 4.500e+04 1.250e+05 9.000e+04]]


In [42]:
print("10e) Last 2 rows:\n", Sales.tail(2))


10e) Last 2 rows:
            2014   2015    2016   2017
Ankit   30000.0  30000  100000  80000
Shruti  40000.0  45000  125000  90000


In [43]:
print("10f) First 2 columns:\n", Sales.iloc[:, 0:2])


10f) First 2 columns:
             2014   2015
Madhu      100.5  12000
Kusum      150.8  18000
Kinshuk    200.9  22000
Ankit    30000.0  30000
Shruti   40000.0  45000


In [44]:
sales2_data = {
    '2018': {
        'Madhu': 160000,
        'Kusum': 110000,
        'Kinshuk': 500000,
        'Ankit': 340000,
        'Shruti': 900000
    }
}

Sales2 = pd.DataFrame(sales2_data)
print("10g) Sales2 DataFrame:\n", Sales2)


10g) Sales2 DataFrame:
            2018
Madhu    160000
Kusum    110000
Kinshuk  500000
Ankit    340000
Shruti   900000


In [45]:
print("10h) Is Sales2 empty?:", Sales2.empty)


10h) Is Sales2 empty?: False


In [47]:
import pandas as pd

# Re-creating the Sales DataFrame
sales_data = {
    '2014': [100.5, 150.8, 200.9, 30000, 40000],
    '2015': [12000, 18000, 22000, 30000, 45000],
    '2016': [20000, 50000, 70000, 100000, 125000],
    '2017': [50000, 60000, 70000, 80000, 90000]
}
sales_index = ['Madhu', 'Kusum', 'Kinshuk', 'Ankit', 'Shruti']
Sales = pd.DataFrame(sales_data, index=sales_index)

# Sales2
sales2_data = {
    '2018': {
        'Madhu': 160000,
        'Kusum': 110000,
        'Kinshuk': 500000,
        'Ankit': 340000,
        'Shruti': 900000
    }
}
Sales2 = pd.DataFrame(sales2_data)


In [48]:
Sales = pd.concat([Sales, Sales2], axis=1)
print("a) Appended Sales2 to Sales:\n", Sales)


a) Appended Sales2 to Sales:
             2014   2015    2016   2017    2018
Madhu      100.5  12000   20000  50000  160000
Kusum      150.8  18000   50000  60000  110000
Kinshuk    200.9  22000   70000  70000  500000
Ankit    30000.0  30000  100000  80000  340000
Shruti   40000.0  45000  125000  90000  900000


In [49]:
Sales = Sales.T
print("b) Transposed Sales:\n", Sales)


b) Transposed Sales:
          Madhu     Kusum   Kinshuk     Ankit    Shruti
2014     100.5     150.8     200.9   30000.0   40000.0
2015   12000.0   18000.0   22000.0   30000.0   45000.0
2016   20000.0   50000.0   70000.0  100000.0  125000.0
2017   50000.0   60000.0   70000.0   80000.0   90000.0
2018  160000.0  110000.0  500000.0  340000.0  900000.0


In [50]:
print("c) Sales in 2017:\n", Sales.loc['2017'])


c) Sales in 2017:
 Madhu      50000.0
Kusum      60000.0
Kinshuk    70000.0
Ankit      80000.0
Shruti     90000.0
Name: 2017, dtype: float64


In [51]:
print("d) Madhu and Ankit in 2017 & 2018:\n", Sales.loc[['2017', '2018'], ['Madhu', 'Ankit']])


d) Madhu and Ankit in 2017 & 2018:
          Madhu     Ankit
2017   50000.0   80000.0
2018  160000.0  340000.0


In [52]:
print("e) Shruti in 2016:\n", Sales.loc['2016', 'Shruti'])


e) Shruti in 2016:
 125000.0


In [53]:
Sales['Sumeet'] = [196.2, 37800, 52000, 78438, 38852]
print("f) Added Sumeet:\n", Sales)


f) Added Sumeet:
          Madhu     Kusum   Kinshuk     Ankit    Shruti   Sumeet
2014     100.5     150.8     200.9   30000.0   40000.0    196.2
2015   12000.0   18000.0   22000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0   70000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   70000.0   80000.0   90000.0  78438.0
2018  160000.0  110000.0  500000.0  340000.0  900000.0  38852.0


In [54]:
Sales = Sales.drop(index='2014')
print("g) Deleted 2014:\n", Sales)


g) Deleted 2014:
          Madhu     Kusum   Kinshuk     Ankit    Shruti   Sumeet
2015   12000.0   18000.0   22000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0   70000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   70000.0   80000.0   90000.0  78438.0
2018  160000.0  110000.0  500000.0  340000.0  900000.0  38852.0


In [55]:
Sales = Sales.drop(columns='Kinshuk')
print("h) Deleted Kinshuk:\n", Sales)


h) Deleted Kinshuk:
          Madhu     Kusum     Ankit    Shruti   Sumeet
2015   12000.0   18000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   80000.0   90000.0  78438.0
2018  160000.0  110000.0  340000.0  900000.0  38852.0


In [56]:
Sales = Sales.rename(columns={'Ankit': 'Vivaan', 'Madhu': 'Shailesh'})
print("i) Renamed Ankit & Madhu:\n", Sales)


i) Renamed Ankit & Madhu:
       Shailesh     Kusum    Vivaan    Shruti   Sumeet
2015   12000.0   18000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   80000.0   90000.0  78438.0
2018  160000.0  110000.0  340000.0  900000.0  38852.0


In [57]:
Sales.at['2018', 'Shailesh'] = 100000
print("j) Updated Shailesh 2018 sale:\n", Sales)


j) Updated Shailesh 2018 sale:
       Shailesh     Kusum    Vivaan    Shruti   Sumeet
2015   12000.0   18000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   80000.0   90000.0  78438.0
2018  100000.0  110000.0  340000.0  900000.0  38852.0


In [58]:
Sales.to_csv('SalesFigures.csv', index=False, header=False)
print("k) Written to SalesFigures.csv without labels")


k) Written to SalesFigures.csv without labels


In [59]:
SalesRetrieved = pd.read_csv('SalesFigures.csv', header=None)
SalesRetrieved.index = Sales.index
SalesRetrieved.columns = Sales.columns
print("l) SalesRetrieved with labels:\n", SalesRetrieved)


l) SalesRetrieved with labels:
       Shailesh     Kusum    Vivaan    Shruti   Sumeet
2015   12000.0   18000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   80000.0   90000.0  78438.0
2018  100000.0  110000.0  340000.0  900000.0  38852.0


In [ ]:
from google.colab import drive
drive.mount('/content/drive')